### ISSUE TITLE
Line 118 - Bug report

### ISSUE THREAD

**Issue by blakejones99** [Stryder76/ProdPsychosisUS#1]
**Line 118**
{"success":false,"error":"NotFound","message":"Task not found."}

**To Reproduce**
Run code from google script or go to the link on line 118

**Expected behaviour**
Be taken to the page

**Helpful media**
![image](https://user-images.githubusercontent.com/90980135/168255852-4a538880-572d-4d42-8c94-6a6ba58576ae.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome

**Comment by Stryder76** [comment]
Did you get the code from the release?

If you did or didn't could you provide a copy of the code you have? (make sure to remove your token, I always almost forget that when committing), I want to make figure out where I went wrong. I won't be on my PC for ~15h, so help may be slow.

I will also examine the code from the default of the release for comparison purposes.

Did you modify anything to suit you better?

**Comment by Stryder76** [comment]
I just looked at the code again and I realized that I used the task ID of my own daily instead of a variable. I will fix it ASAP. I don't think I need much further input from you.

**Comment by blakejones99** [comment]
Awesome! Thanks!

**Comment by Stryder76** [comment]
I have replaced my task ID with a valid variable, and the bug should be fixed. Feel free to open a new issue if you need anything else.
